
import streamlit as st
import requests
import datetime
import json

BASE_URL = "http://localhost:8000"  # Backend endpoint

st.set_page_config(
    page_title="🤖 Multi-Agent AI System",
    page_icon="🤖",
    layout="wide",
    initial_sidebar_state="expanded",
)

st.title("🤖 Multi-Agent AI System")

# Initialize chat history
if "messages" not in st.session_state:
    st.session_state.messages = []

if "agent_logs" not in st.session_state:
    st.session_state.agent_logs = []

# Sidebar for agent information
with st.sidebar:
    st.header("📊 Agent Information")
    st.info("""
    **Available Agents:**
    - 🔍 **Supervisor**: Routes queries to appropriate agents
    - 🌐 **Agent 1**: Web search, weather, places
    - 🧠 **Agent 2**: Complex tasks routing
    - 📚 **Researcher**: Web search & research
    - 💻 **Coder**: DSA & programming problems
    - ✍️ **Writer**: Content polishing
    """)
    
    st.divider()
    
    # Display agent logs
    if st.session_state.agent_logs:
        st.subheader("🔄 Agent Workflow")
        for log in st.session_state.agent_logs[-5:]:  # Show last 5 logs
            st.caption(f"**{log['agent']}**: {log['action']}")

# Main chat interface
st.header("How can I help you?")

# Create two columns for better layout
col1, col2 = st.columns([3, 1])

with col1:
    user_input = st.text_area(
        "Enter your query",
        placeholder="Ask me anything: research topics, coding problems, web search...",
        height=100,
        key="user_input"
    )

with col2:
    submit_button = st.button("🚀 Send", use_container_width=True)

if submit_button and user_input.strip():
    try:
        # Add user message to chat history
        st.session_state.messages.append({
            "role": "user",
            "content": user_input,
            "timestamp": datetime.datetime.now()
        })
        
        # Show thinking spinner while backend processes
        with st.spinner("🤔 Processing through agent workflow..."):
            payload = {"question": user_input}
            response = requests.post(f"{BASE_URL}/query", json=payload, timeout=60)

        if response.status_code == 200:
            result = response.json()
            answer = result.get("answer", "No answer returned.")
            agent_path = result.get("agent_path", [])
            
            # Log agent workflow
            if agent_path:
                st.session_state.agent_logs.append({
                    "agent": " → ".join(agent_path),
                    "action": "Completed workflow"
                })
            
            # Add bot message to chat history
            st.session_state.messages.append({
                "role": "assistant",
                "content": answer,
                "agent_path": agent_path,
                "timestamp": datetime.datetime.now()
            })
            
            # Display the response with formatting
            with st.container(border=True):
                col1, col2 = st.columns([4, 1])
                
                with col1:
                    st.markdown(f"**Generated:** {datetime.datetime.now().strftime('%Y-%m-%d at %H:%M')}")
                
                with col2:
                    if agent_path:
                        st.caption(f"🔄 Path: {' → '.join(agent_path)}")
                
                st.divider()
                st.markdown(answer)
                st.divider()
                
                st.caption("*This response was generated by an AI multi-agent system. Please verify critical information.*")
        
        else:
            st.error(f"❌ Bot failed to respond: {response.text}")
            st.session_state.agent_logs.append({
                "agent": "System",
                "action": f"Error: {response.status_code}"
            })

    except requests.exceptions.Timeout:
        st.error("⏱️ Request timed out. The agent workflow took too long to process.")
    except requests.exceptions.ConnectionError:
        st.error("🔗 Failed to connect to the backend. Make sure the server is running on http://localhost:8000")
    except Exception as e:
        st.error(f"❌ An error occurred: {str(e)}")
        st.session_state.agent_logs.append({
            "agent": "System",
            "action": f"Exception: {str(e)}"
        })

# Display chat history
if st.session_state.messages:
    st.divider()
    st.subheader("💬 Chat History")
    
    for msg in st.session_state.messages:
        if msg["role"] == "user":
            st.write(f"**👤 You:** {msg['content']}")
        else:
            agent_info = ""
            if "agent_path" in msg:
                agent_info = f" *[{' → '.join(msg['agent_path'])}]*"
            st.write(f"**🤖 Assistant{agent_info}:** {msg['content'][:200]}...")
        st.caption(msg["timestamp"].strftime("%H:%M:%S"))